### ISSUE TITLE
How to log in for the first time

### ISSUE THREAD

**Issue by klettervirus** [gymdb/speechday#10]
Dear people at linuxbildung.at!
I would like to use your software for our school. I installed the package on a strato webhosting package. All went well, I can get to the login page. From there I have no idea how to login: Where do I provide the admin credentials? Or, where do I obtain those? Do I have to manually edit a file on the server? Is there a standardized admin? (Wouldn´t think so - but I have no idea where to get/put the admin login data!)
BTW, I love your open source movement/initiative!
Kindest regards, Stefan

**Comment by letsknowingcrumbs** [comment]
Hi Klettervirus,
Hat Strato überhaupt die Option eine Datenbank mit dem Richtigen Namen (speechday) anzulegen?

"HINWEIS:
Wenn Sie ein aktuelles Hosting Paket haben, dann sieht bei Ihnen der
Datenbankname: dbs####### und der
Benutzername: dbu####### so aus."
laut Strato

**Comment by letsknowingcrumbs** [comment]
nö ich glaube nicht also 
settings.ini file contained in code/dao bearbeiten.

<?php return; ?>
; database settings for speechday database

[SQL]
host = localhost
user = DBUSER
password = 'DBPASSWORD'
dbname = DBNAME

**Comment by letsknowingcrumbs** [comment]
aso: admin admin
