### ISSUE TITLE
Raumeinstellungen ändern

### ISSUE THREAD

**Issue by andischieler** [gymdb/speechday#11]
Guten Tag,
vielen Dank für das großartige Tool. 
Ich würde gerne in teacher.php ein Panel "Raumeinstellungen" ergänzen, in dem jeder Lehrer / jede Lehrerin ihren Raumname und ihre Raumnummer selbst ändern bzw. eingeben kann. 
Dazu habe ich in teacher.php folgendes ab Zeile 101 ergänzt:

		
		<div class='panel panel-default'>
            <div class='panel-heading'>
                <h4 class='panel-title'>
                    <a data-toggle='collapse' data-parent='#accordion' href='#collapse3'>
                        Raumeinstellungen
                    </a>
                </h4>
            </div>
            <div id='collapse3' class='panel-collapse collapse'>
                <div class='panel-body'>
					
					<p><?php
					$viewController = ViewController::getInstance();
					$id_now = escape($user->getId());
					
					$handle = fopen ("code/dao/settings.ini.php", "r");
					while ( $inhalt = fgets ($handle, 4096 ))
					{
						if (substr($inhalt,0,4) == "host") { $xhost = trim(substr(trim(strstr($inhalt, '=')),1)); }
						if (substr($inhalt,0,4) == "user") { $xuser = trim(substr(trim(strstr($inhalt, '=')),1)); }
						if (substr($inhalt,0,8) == "password") { $xpass = substr(substr(trim(substr(trim(strstr($inhalt, '=')),1)),1),0,-1); }
						if (substr($inhalt,0,6) == "dbname") { $xdbname = trim(substr(trim(strstr($inhalt, '=')),1)); }
					}
					fclose($handle);	
						
					$db = new mysqli($xhost,$xuser,$xpass,$xdbname);
					$sql = "SELECT id,roomNumber,name,teacherId FROM room WHERE teacherId= $id_now LIMIT 1";
					$erg = $db->query($sql);
					if ($erg->num_rows) {
						$anz = $erg->num_rows;
						$datensatz = $erg->fetch_assoc();
						$existdates = 1;
					} else { $existdates = 0; }
					
					if ($existdates === 1) {
						if(($_POST['roomName'] != "") and (($datensatz['name'] !=  $_POST['roomName']) or ($datensatz['roomNumber'] !=  $_POST['roomNumber']))) {
							$neuername = $_POST['roomName'];
							$neuenummer = $_POST['roomNumber'];
							$sqlup = 'UPDATE room SET name="'. $neuername .'", roomNumber="'. $neuenummer .'" WHERE teacherId="'. $id_now .'" LIMIT 1';
							if ($db->query($sqlup)) {
								echo '<p>Upate erfolgreich!</p>';
							} else { 
								echo '<p>Upate fehlgeschlagen!</p>';
							}
						}
					} elseif (($existdates === 0) and (($_POST['roomName'] != "") or ($_POST['roomNumber'] != ""))) {
						if ($_POST['roomName'] != "") { $neuername = $_POST['roomName']; } else { $neuername = '-'; }
						if ($_POST['roomNumber'] != "") { $neuenummer = $_POST['roomNumber']; } else { $neuenummer = 0; }
						$sqlin = "INSERT INTO room (name,roomNumber,teacherId) VALUES ('{$neuername}',{$neuenummer},{$id_now})";
							if ($db->query($sqlin)) {
								echo '<p>Neuer Raum erfolgreich angelegt!</p>';
							} else { 
								echo '<p>Anlegen von neuem Raum fehlgeschlagen!</p>';
							}
					}
					
					?></p>
                    <h4>Aktuelle Raumeinstellungen</h4>
                    <p id='attendance'>
                        <?php
						$sql = "SELECT id,roomNumber,name,teacherId FROM room WHERE teacherId= $id_now LIMIT 1";
						$erg = $db->query($sql);
						$datensatz = $erg->fetch_assoc();
						if ($datensatz['id']) {
							if (substr($datensatz['name'],0,4) == 'http') {
								echo '<p>Link zum Raum: <a href="'. $datensatz['name'] .'">'. $datensatz['name'] .'</a></p>';
							} else {
								echo '<p>Raumname: '. $datensatz['name'] .'<br>Raumnummer: '. $datensatz['roomNumber'] .'</p>';
							}
						} else { 
							echo '<p>Kein Raum angegeben.</p>';
						}
                        ?>
                    </p>

                    <?php if ($attendance != null): ?>
                    <h4>
                        Raumeinstellung ändern
                    </h4>
                    <form action="<?php echo $_SERVER['PHP_SELF']; ?>#collapse3" id='editUsersForm' method="post">
						<div id='changeUserForm'> 
                        <input type='hidden' name='userId' value='<?php echo(escape($user->getId())) ?>'>
							<div id='inputRoomName-div' class='form-group'> 
								<label for='inputRoomName'>Raumname</label>
								<input type='text' class='form-control' id='inputRoomName' name='roomName' placeholder='<?php echo $datensatz['name']; ?>' value='<?php echo $datensatz['name']; ?>'>
								<p>Hier können sie auch statt eines Raumnamens einen Link, z. B. für Online-Meetings eingeben.<br>Der Link muss mit <i>http</i> beginnen!</p>
							</div>
							<div id='inputRoomNumber-div' class='form-group'> 
								<label for='inputRoomNumber'>Raumummer</label>
								<input type='text' class='form-control' id='inputRoomNumber' name='roomNumber' placeholder='<?php echo $datensatz['roomNumber']; ?>' value='<?php echo $datensatz['roomNumber']; ?>'>
							</div>					

                        <button type='submit' class='btn btn-primary' id='btn-edit-user'>
                            Raum ändern
                        </button>
                    </div>
					</form>
					
                    <div class='message' id='message'></div>

                    <?php endif; ?>
                </div>
            </div>
        </div>

Wie kann ich die gewünschten Werte und Aktionen unsetzen?

Viele Grüße
Andreas

**Comment by speedy-10** [comment]
Ja, das würde ich auch begrüßen, wenn es aufgenommen werden würde.

**Comment by gymdb** [comment]
fixed
