### ISSUE TITLE
Bessere Suche als Admin in Statistik

### ISSUE THREAD

**Issue by speedy-10** [gymdb/speechday#14]
Hallo zusammen,
wir sind eine große Schule mit > 1100 Schülern.
Wenn ich mich als Admin anmelde, dann unter Administration > Statistik einen bestimmten Nutzer suche, dann werden scheinbar nur die ersten 2 Buchstaben berücksichtigt.
Bei Namen wie z.B. "Schwarz" muss man dann recht viele Namen durchsuchen, die alle mit "sc" beginnen.

Also wenn diese Suche z.B. 5 oder 6 Buchstaben berücksichtigen würde, wäre das eine kleine Verbesserung.

Das bitte als "feature request" ansehen, kein Fehler.

Vielen Dank für die tolle Software!

**Comment by bwurst** [comment]
An der Stelle wird bei meiner Installation (~400 Nutzer) keinerlei Suchfunktion sondern ein simples Dropdown-Feld angezeigt. Wie der Browser da bei der Suche unterstützt, kann Speechday eigentlich nicht beinflussen.
Aber ja, das Dropdown ist sicherlich unhandlich bei vielen Nutzern.

**Comment by speedy-10** [comment]
Ja, aber das Menu reagiert auf 2 Buchstabeneingaben.

**Comment by bwurst** [comment]
Aber das ist doch Sache des Browsers. Ich finde keinen Code in Speechday, der diese Suche ausführen sollte.

In meinem Firefox reagiert das (nicht nur hier sondern auf jeder Website) auf so viele Buchstaben wie ich tippen kann bis ich eine Sekunde Pause mache. Ich kann einen kompletten Namen tippen und habe den ausgewählt.

**Comment by speedy-10** [comment]
Ok, danke, ich wusste nicht, dass diese Zeitspanne 1s das ganze beendet und vom Browser abhängt.
