### ISSUE TITLE
Fehlgeschlagene Logins loggen

### ISSUE THREAD

**Issue by bwurst** [gymdb/speechday#15]
Momentan wird jeder Login-Versuch schon vor dem Prüfen des Passworts als Login geloggt und zwar mit Zuordnung der User-Id.
So kann man als Admin gar nicht erkennen, ob ein Login funktioniert hat oder nicht. 

Ich habe aktuell einen Support-Request, dass ein User sich nicht einloggen kann und ich wüsste gerne, ob das mehrere User betrifft. Ich habe die Passwort-Hashes von Moodle übernommen (sind alle im selben crypt-Format) und bei mit meinem Benutzer funktioniert das auch. Wüsste jetzt gerne ob das bei mehreren Benutzern Probleme macht oder nicht.

Ich schlage daher vor, zumindest fehlgeschlagene Logins separat zu loggen.

**Comment by bwurst** [comment]
Der konkrete Fall übrigens lag daran, dass die Usernames bei uns Kleinbuchstaben sind und die Handy-Eingabefelder den ersten Buchstaben groß schreiben. Moodle ist da offenbar case-insensitive.

**Comment by gymdb** [comment]
fixed
