### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by Muensteraner** [gymdb/speechday#16]
Dear Team,
Is it possible to save the system data in flat files in addition to the SQL database? This would help many small schools to use the system quickly. Unfortunately, we do not have database access and want to be able to backup and import or edit the data portable and quickly if necessary. We would be happy about the option of setting up the whole thing without SQL and using the CSV Flatflie system.

Regards

**Comment by gymdb** [comment]
sorry, this is not an option for us and therefore will not be implemented.
t.
