### ISSUE TITLE
Probleme beim Login

### ISSUE THREAD

**Issue by michaelblank5577** [gymdb/speechday#17]
Moin,

habe die Software auf unserem Server installiert, Datenbank eingebaut, wenn ich nun den Login aufrufe, versuche ich mich mit Benutzer: admin und Passwort: Admin zum ersten mal einzuloggen und erhalte folgende Fehlermeldung:

SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

Jemand eine Idee was ich falsch mache?

**Comment by gymdb** [comment]
make sure your settings.ini.php has the correct credentials for the database
