### ISSUE TITLE
Feature Request: zusätzlicher Buchungsbeginn

### ISSUE THREAD

**Issue by speedy-10** [gymdb/speechday#18]
Aktuell gibt es unter Administration ein "Buchungsende". Für manche Schulen wäre es hilfreich, wenn man zusätzlich z.B. einen "Buchungs**beginn**" für **Eltern** zusätzlich angeben könnte. Z.B. wenn eine Klassenstufe wegen eines 2-wöchigen Betriebspraktikums ihre Zugangscodes schon 2 Wochen vor den anderen Schülern bekommt. Dann könnten diese direkt Termine buchen und andere Eltern haben dadurch Nachteile. (Derzeit kann das nur über den direkten Zugriff des Webservers erfolgen, indem man diesen manuell aktiviert bzw. deaktiviert, was etwas umständlich ist.)

**Comment by gymdb** [comment]
fixed
