### ISSUE TITLE
Eingabefeld für Bemerkungen

### ISSUE THREAD

**Issue by sbwheelz** [gymdb/speechday#9]
Hallo zusammen,

als erstes möchte ich mich für dieses super Tool bedanken. Es ist sehr übersichtlich und auch für wenig affine Eltern gut nutzbar.
Da wir aus verschiedenen Gründen die Videokonferenzfunktion leider nicht nutzen können und wir stattdessen einen telefonischen Eltersprechtag abhalte, wäre es sehr hilfreich, wenn es für die Schüler/Eltern die Möglichkeit gäbe, eine aktuelle Telefonnummer zu hinterlegen. Diese sollte dann idealer Weise im Plan der Lehrkraft erscheinen, sodass diese dann die Eltern anrufen kann.

Wir würden uns sehr freuen, wenn es hier eine Lösung geben würde.

Viele Grüße, bleibt gesund und macht weiter so,
Sebastian

**Comment by badgerhill** [comment]
Hallo Sebastian,

nachdem es eine Lösung mit Videokonferenz gibt, werden wir deinen Vorschlag nicht umsetzen. Darüber hinaus würde ich erwarten, dass Lehrerinnen und Lehrer die notwendigen Telefonnummern in irgendeiner Form zur Verfügung stehen. 

Thomas
